name: Flutter CI

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/flutter_ci.yml'
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/flutter_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.x'
        channel: 'stable'
        cache: true
    
    - name: Cache pub dependencies
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    - name: Get dependencies
      working-directory: ./app
      run: flutter pub get
    
    - name: Analyze code
      working-directory: ./app
      run: flutter analyze --fatal-infos
    
    - name: Run tests
      working-directory: ./app
      run: flutter test --coverage
    
    - name: Build APK
      working-directory: ./app
      run: flutter build apk --debug
    
    - name: Build iOS (dry run)
      working-directory: ./app
      run: flutter build ios --debug --no-codesign
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./app/coverage/lcov.info
        fail_ci_if_error: false
